name: Docker Image CI

on:
  push:
    branches: [ "*" ]

env:
  IMAGE_NAME: dayan/php-fpm

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin

      - name: Build and push image
        run: docker buildx build . --file Dockerfile --platform linux/amd64,linux/arm64 --tag $IMAGE_NAME:${GITHUB_REF##*/} --push

      - name: Latest tag
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker pull $IMAGE_NAME:${GITHUB_REF##*/}
          docker tag $IMAGE_NAME:${GITHUB_REF##*/} $IMAGE_NAME:latest
          docker push $IMAGE_NAME