name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  IMAGE_NAME: dayan/php-fpm

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:${GITHUB_REF##*/}
    - name: Docker Push
      run: docker push $IMAGE_NAME:${GITHUB_REF##*/}

    - name: Latest tag
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        docker tag $IMAGE_NAME:${GITHUB_REF##*/} $IMAGE_NAME:latest
        docker push $IMAGE_NAME